# Generated by Django 3.0 on 2020-12-08 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, verbose_name='Предмет')),
            ],
            options={
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(verbose_name='Количество баллов')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Обязательность сдачи')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institutions.Subjects', verbose_name='Предмет')),
            ],
            options={
                'verbose_name_plural': 'Минимальные баллы',
            },
        ),
    ]
